---
- name: Nginx Web Server
  hosts: web
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy custom homepage
      copy:
        dest: /var/www/html/index.html
        content: |
          <h1>Welcome to Terraform + Ansible Project!</h1>
          <p>Deployed automatically via CI/CD.</p>
